### ISSUE TITLE
Expanded Panel zoom

### ISSUE THREAD

**Issue by rkimaoui** [B-3PO/angular-material-expansion-panel#15]
Hello there,

First of all, thank you for this great work.
Question: How can i add a zoom effect to expanded panels like in google inbox app ?

Thanks in advance,
Reda

**Comment by B-3PO** [comment]
If by zoom you mean the way that the panels in google inbox grow in width when opened, then i will unfortunately not be able to update the component to change that. The [spec](https://material.google.com/components/expansion-panels.html) states margin on the panel when it is expanded.

You could try adding you own css to animate it.
This should be close to what you want

``` css
md-expansion-panel {
  margin-left: 0;
  margin-right: 0;
  transition: all 0.12s cubic-bezier(0.25, 0.8, 0.25, 1);
}
md-expansion-panel.md-open {
  margin-left: -12px;
  margin-right: -12px;
}
```
